sudo: required

language: node_js
node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=clean
    - TEST_TYPE=build

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - |
    if [ "$TEST_TYPE" = clean ]; then
      npm run clean
    elif [ "$TEST_TYPE" = build ]; then
      npm run build
    fi