sudo: required

language: node_js
node_js:
  - "8"

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - npm run clean
  - npm run build

after_script:
  - cd dist
  - git init
  - git config user.name "JaredTan95"
  - git config user.email "jian.tan@daocloud.io"
  - git add .
  - git commit -m "Update asf-site"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:asf-site
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/apache/incubator-skywalking-website.git
   - secure: "tSxgM/0QB8tqBdqeJS2vHld9qy/uwifDDDb9ylRYJ0jVN0JvVHfhdr9NKTVafYB+dOKlbIvc3FpX3X9NcbVBykXxjLEGFy90Hp/7F/sWV9jnJxR2XDMFiMGnJqv+BeyTU61I/Y975ytU1n7pX8Yj6vsv1ttsEDmlqKXKkRzZTuwtpILA10R0BeKJe/O2ZwW86nGzEIl4u1w9yJAL0GhN9IzxSpGgtf0xztS8Ux3dEV3uaQk3ikVRDcFo7VF+P1aqJSXQwIEPRp9bFcAZeiT4QBMUVCh4h+kmY4MunPmrQtWZJNCy0634HoloVj4kIbxSUhD2EoIWe/OgonfRgKdUo9VZuHCe5FXg83/5Ad1TVWFEN3kifgbB1uzQoUe43+TRTcYv/E7eac9jqRur3t7UJqi8Aee9JwMcuGE3qoOiRgmq5SIS/lYVZ08WsuBoU2W0mQb5n/ZLb+45a/f/iWCxJoUXabzOe98TLqiU81M8wFG8dxznG1bTLnqe04es+6Mw/+TQ7dUY9b6jgwQFjO+SJx9I64OSA0QJgIFBih4jAgJIavZOa8zwpHImD4nUGGkQbLkddcm2BPFopX7A+R3hocordswhcewbfKAseamzkkMi5WiHsVQduIOll69EvCXATvculUtkAfCToTkngYM5V5IQI2k56T0TWFw1ZbggR5w="
