baseURL = "http://localhost:1313"
title = "Apache SkyWalking"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true
hasCJKLanguage = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
#[permalinks]
#blog = "/:section/:year/:filename/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-178891182-1"

# Language configuration

[languages]
[languages.en]
title = "Apache SkyWalking"
description = "Application performance monitor tool for distributed systems, especially designed for microservices, cloud native and container-based (Docker, K8s, Mesos) architectures."
languageName ="English"
time_format_blog = "Jan 2, 2006"
contentDir = "content/en"
weight = 1

[languages.zh]
title = "Apache SkyWalking"
description = "分布式系统的应用性能监控工具，特别针对微服务、云原生和基于容器（Docker、K8s、Mesos）的架构设计。"
languageName ="中文"
contentDir = "content/zh"
time_format_default = "2006年1月2日"
time_format_blog = "2006年1月2日"
weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Everything below this are Site Params

[params]
copyright = "The Apache Software Foundation"
#qrcode = ""
#privacy_policy = "https://policies.google.com/privacy"
apache_policy="Apache SkyWalking, SkyWalking, Apache, the Apache feather logo, and the Apache SkyWalking project logo are either registered trademarks or trademarks of the Apache Software Foundation."

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/rootsongjc/skywalking-website"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/apache/skywalking"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "1e04e992ebb0283cd"

# Enable Algolia DocSearch
algolia_docsearch = true

# Enable Lunr.js offline search
offlineSearch = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/apache/skywalking-website/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/apache/skywalking-website/issues/new/">tell us how we can improve</a>.'

[[Languages.en.menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs"

[[Languages.en.menu.main]]
    name = "Events"
    weight = 20
    url = "/events"

[[Languages.en.menu.main]]
    name = "Blog"
    weight = 30
    url = "/blog"

[[Languages.en.menu.main]]
    name = "Downloads"
    weight = 40
    url = "/downloads"

[[Languages.en.menu.main]]
    name = "Team"
    weight = 50
    url = "/team"

[[Languages.en.menu.main]]
    name = "Links"
    weight = 60

[[Languages.en.menu.main]]
    parent = "Links"
    name = "Apache Software Foundation"
    weight = 1
    url = "http://www.apache.org/"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "GitHub Issue Tracker"
    weight = 2
    url = "https://github.com/apache/skywalking/issues"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "Dev Mailing List"
    weight = 3
    url = "https://lists.apache.org/list.html?dev@skywalking.apache.org"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "License"
    weight = 4
    url = "http://www.apache.org/licenses/"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "Apache Events"
    weight = 5
    url = "http://www.apache.org/events/current-event"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "Security"
    weight = 6
    url = "http://www.apache.org/security/"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "Sponsor and Donate"
    weight = 7
    url = "http://www.apache.org/foundation/sponsorship.html"

[[Languages.en.menu.main]]
    parent = "Links"
    name = "Thanks"
    weight = 8
    url = "http://www.apache.org/foundation/thanks.html"

[[Languages.zh.menu.main]]
    name = "文档"
    weight = 10
    url = "/docs"

[[Languages.zh.menu.main]]
    name = "活动"
    weight = 20
    url = "/events"

[[Languages.zh.menu.main]]
    name = "博客"
    weight = 30
    url = "/blog"

[[Languages.zh.menu.main]]
    name = "下载"
    weight = 40
    url = "/downloads"

[[Languages.zh.menu.main]]
    name = "团队"
    weight = 50
    url = "/team"

[[Languages.zh.menu.main]]
    name = "链接"
    weight = 60

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "Apache Software Foundation"
    weight = 1
    url = "http://www.apache.org/"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "GitHub Issue Tracker"
    weight = 2
    url = "https://github.com/apache/skywalking/issues"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "Dev Mailing List"
    weight = 3
    url = "https://lists.apache.org/list.html?dev@skywalking.apache.org"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "License"
    weight = 4
    url = "http://www.apache.org/licenses/"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "Apache Events"
    weight = 5
    url = "http://www.apache.org/events/current-event"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "Security"
    weight = 6
    url = "http://www.apache.org/security/"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "Sponsor and Donate"
    weight = 7
    url = "http://www.apache.org/foundation/sponsorship.html"

[[Languages.zh.menu.main]]
    parent = "链接"
    name = "Thanks"
    weight = 8
    url = "http://www.apache.org/foundation/thanks.html"

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/asfskywalking"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name ="Slack"
	url = "http://s.apache.org/slack-invite"
	icon = "fab fa-slack"
        desc = "Join us!"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Mailing list"
	url = "https://lists.apache.org/list.html?dev@skywalking.apache.org"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.user]]
	name = "GitHub"
	url = "https://github.com/apache/skywalking"
	icon = "fab fa-github"
        desc = "Development takes place here!"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
